# Dynmap-SimpleClans configuration
debug: false
language:
  layer-disabled: "&cLayer is disabled!"
  no-permission: "&cYou don't have permission!"
  reloading: "&bReloading plugin..."
  not-member: "&cYou must be member of a clan"
  icon-changed: "&bThe icon was set successfully! The change will take effect soon..."
  icon-not-found: "&cIcon not found"
  error-no-icons: "&c* Error, no icons available!" 
  not-visible: "&bYou are no longer visible on the map"
  visible: "&bYou are now visible on the map"
  fee-enabled: "enabled"
  fee-disabled: "disabled"
  verified: "verified"
  unverified: "unverified"
help-command:
  - "&b[Dynmap-SimpleClans] Commands:"
  - "&b/clanmap seticon [iconname] - sets the clan icon"
  - "&c/clanmap reload - reloads the plugin and its configurations"
  - "&b/clanmap help - shows this help"
hide-warring-players: true  # Hides members of clans while the clans are at war
layer:
  homes:
    enable: true
    default-icon: "clanhome"        # Set the icon used if the clan doesn't set one, DON'T type the file extension
    label: "Clan Homes"             # The label for the layer
    format: "{clan} &8(home)"       # Variables: {clan}, {tag}, {member_count}, (more placeholders: https://github.com/RoinujNosde/Dynmap-SimpleClans/wiki/Placeholders), Colors: &1, New line is pipe symbol: |
    layer-priority: 1               # Ordering priority in layer menu (higher shows on top)
    hide-by-default: false          # Make home layer hidden by default
    min-zoom: 0                     # Set minimum zoom level when markers should be visible (0=default, any zoom)
    hidden-markers: []              # Any clan tags added to this list will be hidden from view, include "world:<worldname>" in the list to hide all clan homes in an entire world
  kills:
    enable: true
    label: "Deaths"                 # The label for the layer
    format: "{vtag}&f{victim}|&7(killed by: {atag}&7{attacker}&7)"      # Variables: {victim}, {attacker}, {vtag}, {atag}, Colors: &1, New line is pipe symbol: |
    layer-priority: 20              # Ordering priority in layer menu (higher shows on top)
    hide-by-default: false          # Make home layer hidden by default
    min-zoom: 0                     # Set minimum zoom level when markers should be visible (0=default, any zoom)
    visible-seconds: 300            # How long the marker will stay visible for
    show:
      clan-players: true            # Show deaths of clan players
      civilians: true               # Show deaths of civilians
