name: ${project.name}
main: net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans
version: ${project.version}
website: ${project.url}
author: phaed
authors:
  - RoinujNosde
  - Minat0_
depend:
  - dynmap
  - SimpleClans
commands:
  clanmap:
    description: Map commands
    usage: Syntax error, verify the command usage on /<command> help
permissions:
  simpleclans.map.reload:
    description: Can reload the plugin
  simpleclans.map.list:
    description: Can retrieve the list of icons
  simpleclans.map.icon.bypass:
    description: Can use all icons
  simpleclans.map.seticon:
    description: Can set an icon